// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ActorPictures","status":true,"description":"Manages actor pictures.","parameters":{"actorPictures":"[\"{\\\"actorId\\\":\\\"1\\\",\\\"normalPictures\\\":\\\"[\\\\\\\"Actor1_1\\\\\\\"]\\\",\\\"statePictures\\\":\\\"[]\\\",\\\"damagePictures\\\":\\\"[]\\\"}\",\"{\\\"actorId\\\":\\\"2\\\",\\\"normalPictures\\\":\\\"[\\\\\\\"Actor1_2\\\\\\\"]\\\",\\\"statePictures\\\":\\\"[]\\\",\\\"damagePictures\\\":\\\"[]\\\"}\",\"{\\\"actorId\\\":\\\"3\\\",\\\"normalPictures\\\":\\\"[\\\\\\\"Actor1_3\\\\\\\"]\\\",\\\"statePictures\\\":\\\"[]\\\",\\\"damagePictures\\\":\\\"[]\\\"}\",\"{\\\"actorId\\\":\\\"4\\\",\\\"normalPictures\\\":\\\"[\\\\\\\"Actor1_4\\\\\\\"]\\\",\\\"statePictures\\\":\\\"[]\\\",\\\"damagePictures\\\":\\\"[]\\\"}\",\"{\\\"actorId\\\":\\\"5\\\",\\\"normalPictures\\\":\\\"[\\\\\\\"Actor1_5\\\\\\\"]\\\",\\\"statePictures\\\":\\\"[]\\\",\\\"damagePictures\\\":\\\"[]\\\"}\",\"{\\\"actorId\\\":\\\"6\\\",\\\"normalPictures\\\":\\\"[\\\\\\\"Actor1_6\\\\\\\"]\\\",\\\"statePictures\\\":\\\"[]\\\",\\\"damagePictures\\\":\\\"[]\\\"}\",\"{\\\"actorId\\\":\\\"7\\\",\\\"normalPictures\\\":\\\"[\\\\\\\"Actor1_7\\\\\\\"]\\\",\\\"statePictures\\\":\\\"[]\\\",\\\"damagePictures\\\":\\\"[]\\\"}\",\"{\\\"actorId\\\":\\\"8\\\",\\\"normalPictures\\\":\\\"[\\\\\\\"Actor1_8\\\\\\\"]\\\",\\\"statePictures\\\":\\\"[]\\\",\\\"damagePictures\\\":\\\"[]\\\"}\"]","pictureCalibrations":"[]","animationPictures":"[]","preloadAllPicturesAtEveryScene":"true"}},
{"name":"HDLayout","status":true,"description":"Optimizes screen layout for 1280x720. Adjusts the placement of various windows and gauges.","parameters":{"commonSettings":"","messageWindowWidth":"840","gaugeSettings":"","gaugeWidth":"200","drawGaugeMaxValue":"true","gaugeMaxValueColor":"16","battleSettings":"","gaugeOffsetX":"12","battleCommandWindowWidth":"280","svActorCoordinate":"","svActorBaseX":"960","svActorBaseY":"360","menuSettings":"","drawMenuStatusBackground":"true","skillSettings":"","drawSkillStatusBackground":"true","skillCommandWindowWidth":"320","equipSettings":"","drawEquipStatusBackground":"true","statusWindowWidth":"320","slotWindowWidth":"496","statusSettings":"","drawStatusInfoBackground":"true","paramWindowWidth":"464","infoOffsetX":"28","expOffsetY":"320","paramOffsetX":"48"}},
{"name":"DEBUGTOOL","status":true,"description":"[SC4 v1.0.0] Outil statique de débogage et logs conditionnels.","parameters":{"enabled":"true","selectiveMode":"false","allowedKeys":"[]"}},
{"name":"Hub_Hero","status":true,"description":"[SC4 v1.0.0] Hub central d'accès et d'association pour les entités Hero.","parameters":{}},
{"name":"Bitmap_Composite","status":true,"description":"[SC4 v1.0.0] Compositeur d'images multi-couches pour le système Paperdoll.","parameters":{}},
{"name":"Game_Hero","status":true,"description":"[SC4 v1.0.0] Classe acteur personnalisée pour les héros (Paperdoll & Notetags).","parameters":{}},
{"name":"Character_Hero","status":true,"description":"[SC4 v1.0.0] Contrôleur d'animation et de déplacement pour les personnages Hero.","parameters":{}},
{"name":"Sprite_CharacterIndicator","status":true,"description":"[SC4 v1.0.0] Affiche des indicateurs visuels au-dessus des personnages.","parameters":{}},
{"name":"Spriteset_FightGauges","status":true,"description":"[SC4 v1.0.0] Ensemble de jauges de combat affichées au-dessus des ennemis (HP, MP, AT).","parameters":{}},
{"name":"Sprite_Hero","status":true,"description":"[SC4 v1.0.0] Sprite d'affichage et d'animation pour le Hero (Paperdoll 96x96, 8 dir).","parameters":{}},
{"name":"FightManager","status":true,"description":"[SC4 v1.0.0] Gestionnaire du système de combat ARPG en temps réel.","parameters":{}},
{"name":"IAManager","status":true,"description":"[SC4 v1.0.0] Classe parente de gestion de l'Intelligence Artificielle.","parameters":{}},
{"name":"IA_melee","status":true,"description":"[SC4 v1.0.0] IA spécialisée de Combat au Corps-à-Corps.","parameters":{}},
{"name":"IA_range","status":true,"description":"[SC4 v1.0.0] IA spécialisée de Combat à Distance.","parameters":{}},
{"name":"Enemy_AI","status":true,"description":"[SC4 v1.0.0] Intégrateur d'IA des événements (Hooks Game_Event vers IAManager).","parameters":{}},
{"name":"SC_DataManager","status":true,"description":"[SC4 v1.0.0] Gestionnaire étendu des données SimCraft et persistance.","parameters":{}},
{"name":"Game_Inventory","status":true,"description":"[SC4 v1.0.0] Classe représentant une instance d'inventaire secondaire.","parameters":{}},
{"name":"Game_Inventories","status":true,"description":"[SC4 v1.0.0] Hub gestionnaire des inventaires secondaires ($inventories).","parameters":{}},
{"name":"Scene_Inventory","status":true,"description":"[SC4 v1.0.0] Scène de gestion et de transfert d'inventaires multiples.","parameters":{}},
{"name":"SC4_rmmz_core_Patches","status":true,"description":"[SC4 v1.0.0] Surcharges et patches des classes natives de rmmz_core.js.","parameters":{}},
{"name":"SC4_rmmz_objects_Patches","status":true,"description":"[SC4 v1.0.0] Surcharges et patches des classes natives de rmmz_objects.js.","parameters":{}},
{"name":"SC4_rmmz_scenes_Patches","status":true,"description":"[SC4 v1.0.0] Surcharges et patches des classes natives de rmmz_scenes.js.","parameters":{}},
{"name":"SC4_rmmz_sprites_Patches","status":true,"description":"[SC4 v1.0.0] Surcharges et patches des classes natives de rmmz_sprites.js.","parameters":{}}
];
